import { useState } from "react";
import { useEffect } from "react";
// import { useParams } from "react-router-dom";
import InPageNavigation from "./InPageNavigation.jsx";
import Team1Details from "./Team1Details.jsx";
import Team2Details from "./Team2Details.jsx";

function MatchDetail() {
  // let { id } = useParams();
  //   console.log(id);
  const [matchDetail, setMatchDetail] = useState([]);
  let data = {
    matchInfo: {
      matchId: 118880,
      matchDescription: "67th Match",
      matchFormat: "T20",
      matchType: "league",
      complete: true,
      domestic: false,
      matchStartTimestamp: 1748167200000,
      matchCompleteTimestamp: 1748180118382,
      dayNight: false,
      year: 2025,
      state: "complete",
      team1: {
        id: 971,
        name: "Gujarat Titans",
        playerDetails: [
          {
            id: 11808,
            name: "Shubman Gill",
            fullName: "Shubman Gill",
            nickName: "Shubman Gill",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 616515,
          },
          {
            id: 2258,
            name: "Jos Buttler",
            fullName: "Jos Buttler",
            nickName: "Buttler",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 617407,
            isOverseas: true,
          },
          {
            id: 13748,
            name: "Sherfane Rutherford",
            fullName: "Sherfane Rutherford",
            nickName: "Rutherford",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 594230,
            isOverseas: true,
          },
          {
            id: 10226,
            name: "Shahrukh Khan",
            fullName: "Shahrukh Khan",
            nickName: "Shahrukh Khan",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 226465,
          },
          {
            id: 9693,
            name: "Rahul Tewatia",
            fullName: "Rahul Tewatia",
            nickName: "Rahul Tewatia",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 196288,
          },
          {
            id: 18637,
            name: "Arshad Khan",
            fullName: "Arshad Khan",
            nickName: "Arshad Khan",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 182026,
          },
          {
            id: 10738,
            name: "Rashid Khan",
            fullName: "Rashid Khan",
            nickName: "Rashid Khan",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 616553,
            isOverseas: true,
          },
          {
            id: 13320,
            name: "Gerald Coetzee",
            fullName: "Gerald Coetzee",
            nickName: "Gerald Coetzee",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "GT",
            faceImageId: 597795,
            playingXIChange: "IN",
            isOverseas: true,
          },
          {
            id: 11595,
            name: "Sai Kishore",
            fullName: "Ravisrinivasan Sai Kishore",
            nickName: "Sai Kishore",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "GT",
            faceImageId: 226507,
          },
          {
            id: 10808,
            name: "Siraj",
            fullName: "Mohammed Siraj",
            nickName: "Siraj",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "GT",
            faceImageId: 591952,
          },
          {
            id: 10551,
            name: "Prasidh",
            fullName: "Prasidh Krishna",
            nickName: "Prasidh",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "GT",
            faceImageId: 591958,
            inMatchChange: "MOUT",
          },
          {
            id: 9585,
            name: "Rabada",
            fullName: "Kagiso Rabada",
            nickName: "Rabada",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm fast",
            teamName: "GT",
            faceImageId: 619869,
            playingXIChange: "OUT",
          },
          {
            id: 13866,
            name: "Sai Sudharsan",
            fullName: "Sai Sudharsan",
            nickName: "Sai Sudharsan",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm leg break",
            teamName: "GT",
            faceImageId: 702330,
            playingXIChange: "OUT",
            inMatchChange: "MIN",
            splSubstitute: true,
          },
          {
            id: 702,
            name: "Ishant",
            fullName: "Ishant Sharma",
            nickName: "Ishant",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 154520,
            splSubstitute: true,
          },
          {
            id: 8182,
            name: "Jayant Yadav",
            fullName: "Jayant Yadav",
            nickName: "Jayant Yadav",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 226388,
          },
          {
            id: 8422,
            name: "Shanaka",
            fullName: "Dasun Shanaka",
            nickName: "Shanaka",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "GT",
            faceImageId: 351876,
          },
          {
            id: 10945,
            name: "Washington Sundar",
            fullName: "Washington Sundar",
            nickName: "Washington Sundar",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "GT",
            faceImageId: 616522,
            splSubstitute: true,
          },
          {
            id: 10954,
            name: "Lomror",
            fullName: "Mahipal Lomror",
            nickName: "Lomror",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "GT",
            faceImageId: 226541,
            splSubstitute: true,
          },
          {
            id: 11077,
            name: "Karim Janat",
            fullName: "Karim Janat",
            nickName: "Karim Janat",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "GT",
            faceImageId: 226321,
          },
          {
            id: 12643,
            name: "Kulwant Khejroliya",
            fullName: "Kulwant Khejroliya",
            nickName: "Khejroliya",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "GT",
            faceImageId: 182026,
          },
          {
            id: 13135,
            name: "Anuj Rawat",
            fullName: "Anuj Rawat",
            nickName: "Anuj Rawat",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 226472,
            splSubstitute: true,
          },
          {
            id: 14596,
            name: "Manav Suthar",
            fullName: "Manav Suthar",
            nickName: "Manav Suthar",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "GT",
            faceImageId: 182026,
          },
          {
            id: 15779,
            name: "Kushagra",
            fullName: "Kumar Kushagra",
            nickName: "Kushagra",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "GT",
            faceImageId: 594227,
          },
          {
            id: 22141,
            name: "Gurnoor Brar",
            fullName: "Gurnoor Brar",
            nickName: "Gurnoor Brar",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm fast",
            teamName: "GT",
            faceImageId: 182026,
          },
          {
            id: 22576,
            name: "Nishant Sindhu",
            fullName: "Nishant Sindhu",
            nickName: "Nishant Sindhu",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 971,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "GT",
            faceImageId: 594229,
          },
          {
            id: 269,
            name: "Ashish Nehra",
            fullName: "Ashish Nehra",
            nickName: "Nehra",
            role: "Head coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 155112,
            isSupportStaff: true,
          },
          {
            id: 166,
            name: "Vikram Solanki",
            fullName: "Vikram Solanki",
            nickName: "Solanki",
            role: "Director of Cricket",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 74,
            name: "Parthiv Patel",
            fullName: "Parthiv Patel",
            nickName: "Parthiv Patel",
            role: "Batting coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 152612,
            isSupportStaff: true,
          },
          {
            id: 1423956,
            name: "Naeem Amin",
            fullName: "Naeem Amin",
            nickName: "Naeem Amin",
            role: "Bowling coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 1423951,
            name: "Narender Negi",
            fullName: "Narender Negi",
            nickName: "Narender Negi",
            role: "Fielding coach",
            teamId: 971,
            teamName: "GT",
            faceImageId: 182026,
            isSupportStaff: true,
          },
        ],
        shortName: "GT",
      },
      team2: {
        id: 58,
        name: "Chennai Super Kings",
        playerDetails: [
          {
            id: 1431163,
            name: "Ayush Mhatre",
            fullName: "Ayush Mhatre",
            nickName: "Ayush Mhatre",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "CSK",
            faceImageId: 182026,
          },
          {
            id: 9838,
            name: "Conway",
            fullName: "Devon Conway",
            nickName: "Conway",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm medium",
            teamName: "CSK",
            faceImageId: 616434,
            inMatchChange: "MOUT",
            splSubstitute: false,
            isOverseas: true,
          },
          {
            id: 13476,
            name: "Urvil Patel",
            fullName: "Urvil Patel",
            nickName: "Urvil Patel",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "CSK",
            faceImageId: 182026,
          },
          {
            id: 587,
            name: "Ravindra Jadeja",
            fullName: "Ravindra Jadeja",
            nickName: "Jadeja",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "CSK",
            faceImageId: 616520,
          },
          {
            id: 20538,
            name: "Dewald Brevis",
            fullName: "Dewald Brevis",
            nickName: "Brevis",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "CSK",
            faceImageId: 594284,
            isOverseas: true,
          },
          {
            id: 11195,
            name: "Shivam Dube",
            fullName: "Shivam Dube",
            nickName: "Shivam Dube",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm medium",
            teamName: "CSK",
            faceImageId: 593805,
          },
          {
            id: 9427,
            name: "Deepak Hooda",
            fullName: "Deepak Hooda",
            nickName: "Hooda",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "CSK",
            faceImageId: 244970,
            playingXIChange: "IN",
          },
          {
            id: 265,
            name: "Dhoni",
            fullName: "MS Dhoni",
            nickName: "Dhoni",
            captain: true,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "CSK",
            faceImageId: 170677,
          },
          {
            id: 14598,
            name: "Anshul Kamboj",
            fullName: "Anshul Kamboj",
            nickName: "Anshul Kamboj",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "CSK",
            faceImageId: 182026,
          },
          {
            id: 15452,
            name: "Noor Ahmad",
            fullName: "Noor Ahmad",
            nickName: "Noor Ahmad",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "CSK",
            faceImageId: 616569,
            isOverseas: true,
          },
          {
            id: 10952,
            name: "Khaleel Ahmed",
            fullName: "Khaleel Ahmed",
            nickName: "Khaleel Ahmed",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "CSK",
            faceImageId: 655386,
          },
          {
            id: 1593,
            name: "Ashwin",
            fullName: "Ravichandran Ashwin",
            nickName: "Ashwin",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "CSK",
            faceImageId: 591961,
            playingXIChange: "OUT",
            splSubstitute: true,
          },
          {
            id: 16458,
            name: "Matheesha Pathirana",
            fullName: "Matheesha Pathirana",
            nickName: "Pathirana",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "CSK",
            faceImageId: 351888,
            playingXIChange: "OUT",
            inMatchChange: "MIN",
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 8204,
            name: "Vijay Shankar",
            fullName: "Vijay Shankar",
            nickName: "Shankar",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "CSK",
            faceImageId: 170664,
            splSubstitute: true,
          },
          {
            id: 9012,
            name: "Tripathi",
            fullName: "Rahul Tripathi",
            nickName: "Tripathi",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "CSK",
            faceImageId: 594322,
          },
          {
            id: 9746,
            name: "Shreyas Gopal",
            fullName: "Shreyas Gopal",
            nickName: "Shreyas Gopal",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "CSK",
            faceImageId: 226505,
          },
          {
            id: 11177,
            name: "Rachin Ravindra",
            fullName: "Rachin Ravindra",
            nickName: "Ravindra",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "CSK",
            faceImageId: 655385,
          },
          {
            id: 12092,
            name: "K Nagarkoti",
            fullName: "Kamlesh Nagarkoti",
            nickName: "K Nagarkoti",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "CSK",
            faceImageId: 226313,
            splSubstitute: true,
          },
          {
            id: 13184,
            name: "Mukesh Choudhary",
            fullName: "Mukesh Choudhary",
            nickName: "Mukesh Choudhary",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "CSK",
            faceImageId: 182026,
          },
          {
            id: 15480,
            name: "Nathan Ellis",
            fullName: "Nathan Ellis",
            nickName: "Nathan Ellis",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "CSK",
            faceImageId: 619885,
          },
          {
            id: 22571,
            name: "Shaik Rasheed",
            fullName: "Shaik Rasheed",
            nickName: "Shaik Rasheed",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "CSK",
            faceImageId: 594287,
          },
          {
            id: 32835,
            name: "Ramakrishna Ghosh",
            fullName: "Ramakrishna Ghosh",
            nickName: "Ramakrishna Ghosh",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "CSK",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 1427488,
            name: "Andre Siddarth C",
            fullName: "Andre Siddarth C",
            nickName: "Andre Siddarth C",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 58,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "CSK",
            faceImageId: 182026,
          },
          {
            id: 49,
            name: "Stephen Fleming",
            fullName: "Stephen Fleming",
            nickName: "Stephen Fleming",
            role: "Head coach",
            teamId: 58,
            teamName: "CSK",
            faceImageId: 151497,
            isSupportStaff: true,
          },
          {
            id: 4772,
            name: "Michael Hussey",
            fullName: "Michael Hussey",
            nickName: "M Hussey",
            role: "Batting coach",
            teamId: 58,
            teamName: "CSK",
            faceImageId: 180290,
            isSupportStaff: true,
          },
          {
            id: 5487,
            name: "Eric Simons",
            fullName: "Eric Simons",
            nickName: "Simons",
            role: "Bowling Consultant",
            teamId: 58,
            teamName: "CSK",
            faceImageId: 157813,
            isSupportStaff: true,
          },
          {
            id: 42611,
            name: "Rajiv Kumar",
            fullName: "Rajiv Kumar",
            nickName: "Rajiv Kumar",
            role: "Fielding coach",
            teamId: 58,
            teamName: "CSK",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 3942,
            name: "Sridharan Sriram",
            fullName: "Sridharan Sriram",
            nickName: "Sriram",
            role: "Assistant Coach",
            teamId: 58,
            teamName: "CSK",
            faceImageId: 182026,
            isSupportStaff: true,
          },
        ],
        shortName: "CSK",
      },
      series: {
        id: 9237,
        name: "Indian Premier League 2025",
        seriesType: "IPL",
        startDate: 1742515200000,
        endDate: 1748995200000,
        seriesFolder: "",
        odiSeriesResult: "",
        t20SeriesResult: "",
        testSeriesResult: "",
        tournament: true,
      },
      umpire1: {
        id: 8200,
        name: "Kaushik Gandhi",
        country: "IND",
      },
      umpire2: {
        id: 8871,
        name: "KN Anantha Padmanabhan",
        country: "IND",
      },
      umpire3: {
        id: 8862,
        name: "Nitin Menon",
        country: "IND",
      },
      referee: {
        id: 8864,
        name: "Amit Sharma",
        country: "IND",
      },
      tossResults: {
        tossWinnerId: 58,
        tossWinnerName: "Chennai Super Kings",
        decision: "Batting",
      },
      result: {
        resultType: "win",
        winningTeam: "Chennai Super Kings",
        winningteamId: 58,
        winningMargin: 83,
        winByRuns: true,
        winByInnings: false,
      },
      venue: {
        id: 50,
        name: "Narendra Modi Stadium",
        city: "Ahmedabad",
        country: "India",
        timezone: "+05:30",
        latitude: "23.091785",
        longitude: "72.597465",
      },
      status: "Chennai Super Kings opt to bat",
      playersOfTheMatch: [
        {
          id: 20538,
          name: "Dewald Brevis",
          fullName: "Dewald Brevis",
          nickName: "Brevis",
          captain: false,
          keeper: false,
          substitute: false,
          teamName: "South Africa U19",
          faceImageId: 594284,
        },
      ],
      playersOfTheSeries: [],
      revisedTarget: {
        reason: "",
      },
      matchTeamInfo: [
        {
          battingTeamId: 58,
          battingTeamShortName: "CSK",
          bowlingTeamId: 971,
          bowlingTeamShortName: "GT",
        },
        {
          battingTeamId: 971,
          battingTeamShortName: "GT",
          bowlingTeamId: 58,
          bowlingTeamShortName: "CSK",
        },
      ],
      isMatchNotCovered: false,
      HYSEnabled: 1,
      livestreamEnabled: false,
      isFantasyEnabled: true,
      livestreamEnabledGeo: [
        "MA",
        "KW",
        "EG",
        "TN",
        "JO",
        "MR",
        "US",
        "BH",
        "SD",
        "LY",
        "IR",
        "IQ",
        "SA",
        "MU",
        "SY",
        "AE",
        "LB",
        "DJ",
        "SO",
        "SS",
        "YT",
        "YE",
        "RE",
        "OM",
        "DZ",
        "QA",
        "CA",
        "TD",
        "PS",
      ],
      alertType: "auto",
      shortStatus: "CSK won",
      matchImageId: 702365,
    },
    venueInfo: {
      established: 1982,
      capacity: "132,000",
      knownAs: "Motera Gujarat Stadium, Sardar Patel Stadium",
      ends: "Adani Pavilion End, GMDC End",
      city: "Ahmedabad",
      country: "India",
      timezone: "+05:30",
      homeTeam: "Gujarat, Gujarat Titans",
      floodlights: true,
      curator: "Bagira Thakur",
      profile:
        "<b>Introduction:</b>\n\nPopular as one of the premier cricket grounds in India, the stadium is generally known as the 'Motera Stadium' to avoid confusion with another stadium of the same name in the Navrangpura area. It is owned by the Gujarat Cricket Association and comes under the aegis of the West Zone.\n\n<b>Venue History:</b>\n\nBefore this stadium came into existence, international matches were played at the Ahmedabad Municipal Corporation's stadium, bearing the same name. However, in 1982, the Gujrat government donated a 50-acre land on the banks of the Sabarmati river and the Motera stadium was constructed in a span of only nine months. The first international match to be hosted here was a Test between India and West Indies on November 12, 1983. \n\n<b>Venue Description</b>:\n\nThe Motera stadium has been witness to several important landmarks. It is also the adopted home of the Indian Premier League franchise Rajasthan Royals. The current stands are as follows - GMDC Upper and Lower stands, East Upper and Lower Pavilion, Adani Lower Pavilion, Adani Upper Pavilion, Club Pavilion, and West Pavilion. All stands, except the Club and West Pavilions, consistent two tiers. The Adani Pavilion consists of more than 20 air-conditioned corporate boxes as well as the player dressing rooms. The stadium has 21 entry gates. The ground was renovated in 2006, just before the Champions Trophy. After renovation, state-of-the-art floodlights were added to the stadium along with covered stands, three new pitches and a new outfield.\n\n<b>How does the pitch play?</b>\n\nThe Motera offers a slow wicket. Initially, it was a bowler-friendly track but over the course of time, the pitch lost its spice as it started to slow down. Very few Test games have reached a conclusion over here.\n\n<b>Trivia</b>:\n\nSunil Gavaskar became the first-ever cricketer to score 10,000 runs in Test cricket on this ground - a feat he achieved against Pakistan in 1986-87.\n\nKapil Dev claimed his 432nd Test wicket on this ground to become the highest wicket-taker in the world, breaking Sir Richard Hadlee's record in 1993.\n\nby <b>Sonali Dhulap</b>",
      imageUrl:
        "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/50.jpg",
      ground: "Narendra Modi Stadium",
      groundLength: 0,
      groundWidth: 0,
      otherSports: null,
    },
    broadcastInfo: [
      {
        country: "IN",
        broadcaster: [
          {
            broadcastType: "Streaming",
            value: "JioHotstar",
          },
          {
            broadcastType: "TV",
            value: "Star Sports Network",
          },
        ],
      },
    ],
  };

  // async function fetchMatchDetail() {
  //   const url = `https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/${id}`;
  //   const options = {
  //     method: "GET",
  //     headers: {
  //       "x-rapidapi-key": import.meta.env.VITE_API_KEY,
  //       "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
  //     },
  //   };

  //   try {
  //     const response = await fetch(url, options);
  //     const result = await response.json();
  //     setMatchDetail(result);
  //     // console.log(result);
  //   } catch (error) {
  //     console.error(error);
  //   }
  // }

  useEffect(() => {
    // fetchMatchDetail();
    setMatchDetail(data);
    // console.log(console.log(matchDetail))
  }, []);

  return (
    <>
    <div className='text-2xl font-bold text-center m-5'>Match Detail</div>
      {matchDetail.length <= 0 ? (
        <h1>Loading....</h1>
      ) : (
        <InPageNavigation
          teams={[
            matchDetail.matchInfo.team1.shortName,
            matchDetail.matchInfo.team2.shortName,
          ]}
        >
          <Team1Details matchDet={matchDetail} />
          <Team2Details matchDet={matchDetail} />
        </InPageNavigation>
      )}
    </>
  );
}

export default MatchDetail;
